"""
Django settings for front project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

from pathlib import Path
import os

##########################
#                        #
# Change these as needed #
#                        #
##########################
DEMO_USE_SSL = False

# Adding Vagrant host for development
# If you run this demo on www.abc.com then add ".abc.com" to the list!
ALLOWED_HOSTS = ["localhost", "0.0.0.0", "127.0.0.1"]

if DEMO_USE_SSL:
    # https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SECURE_SSL_REDIRECT
    # Set to "no" if necessary; SSL can still be used but you must use the exact https:// address
    SECURE_SSL_REDIRECT = "yes"
    # https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SECURE_PROXY_SSL_HEADER
    # SECURE_PROXY_SSL_HEADER = (X, Y)
    # https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-CSRF_COOKIE_SECURE
    CSRF_COOKIE_SECURE = "yes"

    # https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SESSION_COOKIE_SECURE
    SESSION_COOKIE_SECURE = "yes"


# Change this if you want to run 2 instances from the same folder
DJANGO_DB_FILE = 'db.sqlite3'


#########################
#                       #
# Leave the below alone #
#                       #
#########################

# Start with keychain support and monitoring
WITH_KEYCHAIN = True

KEYCHAIN_HOME = os.getenv('KEYCHAIN_HOME', os.path.join(str(Path.home()), '.keychain'))

KEYCHAIN_CONFIG_FILE = "config/keychain.cfg"
KEYCHAIN_DB_FOLDER = os.getenv('KEYCHAIN_DATA_FOLDER', "data")
KEYCHAIN_DB_FILE = "mitm-back.db"
KEYCHAIN_DB_FILE_PATH = os.path.join(KEYCHAIN_DB_FOLDER, KEYCHAIN_DB_FILE)
if not os.path.exists(KEYCHAIN_DB_FOLDER):
    os.mkdir(KEYCHAIN_DB_FOLDER)


TRUSTED_DIRECTORY_SUFFIX = os.getenv('TD_SUFFIX', '')


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# This is fine to share as long as you never, EVER put this demo in production
SECRET_KEY = '#u+#_0_zo+c+tm1e4se6-duofm3m438o#v=_x6vwxq6+wn8euc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt': "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'mitm.log',
            'formatter': 'verbose'
        },

    },
    'loggers': {
        'mitm': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
        },
    }
}

# Application definition

INSTALLED_APPS = [
    'backend.apps.BackendConfig',
    'polls.apps.PollsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, DJANGO_DB_FILE),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_AUTO_FIELD='django.db.models.AutoField' 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.expanduser('~/keychainmitmdemo.com/static')
MEDIA_ROOT = os.path.expanduser('~/keychainmitmdemo.com/media')
